import { prisma } from "../lib/prisma.js";
import type { RiskQuestion as RiskQuestionRow } from "@prisma/client";

export interface QuestionOption {
  label: string;
  points: number;
}

export interface Question {
  id: string; // RiskQuestion.key
  dimension: 1 | 2;
  order: number;
  text: string;
  helpText: string;
  options: QuestionOption[];
  isActive: boolean;
}

// Shipped defaults, seeded into the DB the first time questions are needed.
// Dimension 1 (order 1-4): informational trigger questions — any option with
// points > 0 flags the assessment for additional review. Dimension 2 (order
// 1-9): scored questions summed into the risk score.
const DIMENSION_1_DEFAULTS: { key: string; text: string; helpText: string }[] = [
  {
    key: "d1_customer_facing",
    text: "Is this an authenticated customer-facing capability?",
    helpText: "Authenticated customers interacting directly with the AI capability.",
  },
  {
    key: "d1_regulated_decisions",
    text: "Does the AI provide recommendations for credit, pricing, eligibility, fraud, AML, HR, or compliance decisions?",
    helpText: "",
  },
  {
    key: "d1_vendor_training_data",
    text: "Does the vendor solution use the organization's customer data for training or fine-tuning?",
    helpText: "Prohibited per standard contract language.",
  },
  {
    key: "d1_full_autonomy",
    text: "Is the AI capability fully autonomous with no human approval or override?",
    helpText: "",
  },
];

const DIMENSION_2_DEFAULTS: { key: string; text: string; helpText: string; options: QuestionOption[] }[] = [
  {
    key: "d2_decision_autonomy",
    text: "Decision Autonomy",
    helpText: "What level of autonomy does the AI have in making outputs and decisions?",
    options: [
      { label: "Assistive/informational only, human reviews or uses output to make decision (e.g. decision support)", points: 1 },
      { label: "Human on the loop, AI acts, human monitors and can override (e.g. fraud monitoring, security monitoring)", points: 3 },
      { label: "Fully automated, no human review", points: 5 },
    ],
  },
  {
    key: "d2_prompt_input_manipulation",
    text: "Prompt / Input Manipulation",
    helpText: "To what extent could user prompts or ingested content override or influence AI behavior or output?",
    options: [
      { label: "Controlled prompt library", points: 1 },
      { label: "Free text user prompts", points: 3 },
      { label: "Autonomous or event based", points: 5 },
    ],
  },
  {
    key: "d2_business_impact",
    text: "Business Impact",
    helpText: "What is the potential business impact if the AI produces incorrect or biased outputs?",
    options: [
      { label: "No impact or minor internal impact", points: 1 },
      { label: "Advisory, operational impact", points: 3 },
      { label: "Customer, financial, and/or regulatory impact", points: 5 },
    ],
  },
  {
    key: "d2_external_interaction",
    text: "External Interaction",
    helpText: "What level of interaction does the AI have with external parties?",
    options: [
      { label: "None, internal use only", points: 1 },
      { label: "Indirect, supports external related decision, but does not engage directly", points: 3 },
      { label: "Direct interaction (e.g. chatbot)", points: 5 },
    ],
  },
  {
    key: "d2_data_sensitivity",
    text: "Data Sensitivity",
    helpText: "What is the highest level of data processed, stored or generated by the AI capability?",
    options: [
      { label: "Public or synthetic data only", points: 1 },
      { label: "Internal or non-sensitive confidential data", points: 3 },
      { label: "Sensitive or regulated confidential data (PCI, PII)", points: 5 },
    ],
  },
  {
    key: "d2_output_content",
    text: "Output Content",
    helpText: "How are AI outputs used and to what extent do they influence or trigger business decisions or actions?",
    options: [
      { label: "Informational, awareness only", points: 1 },
      { label: "Analytical, influences human judgment", points: 3 },
      { label: "Decisioning, drives or triggers actions", points: 5 },
    ],
  },
  {
    key: "d2_explainability",
    text: "Explainability",
    helpText: "How explainable or auditable are AI outputs?",
    options: [
      { label: "Transparent outputs — citations, logs, vendor docs", points: 1 },
      { label: "Moderate interpretability — vendor documentation", points: 3 },
      { label: "Black box — no logs or vendor documentation", points: 5 },
    ],
  },
  {
    key: "d2_accuracy_criticality",
    text: "Accuracy Criticality",
    helpText: "What is the level of reliance on accuracy of AI outputs?",
    options: [
      { label: "Minimal dependence — advisory output that does not influence or support business decisions", points: 1 },
      {
        label:
          "Moderate dependence — output informs human judgement or workflow prioritization, but decisions are subject to independent review",
        points: 3,
      },
      { label: "High dependence — output is routinely relied upon or treated as authoritative, human review is limited", points: 5 },
    ],
  },
  {
    key: "d2_change_autonomy",
    text: "Change Autonomy",
    helpText:
      "What is the risk of model performance degradation, bias, or drift over time (e.g. changes to the model may modify the intended results)?",
    options: [
      { label: "Changes are internally controlled and planned", points: 1 },
      { label: "Changes are vendor managed and planned", points: 3 },
      { label: "Changes are vendor managed but unplanned or self updating/dynamic", points: 5 },
    ],
  },
];

export function toWireQuestion(row: RiskQuestionRow): Question {
  return {
    id: row.key,
    dimension: row.dimension === 1 ? 1 : 2,
    order: row.order,
    text: row.text,
    helpText: row.helpText,
    options: JSON.parse(row.options),
    isActive: row.isActive,
  };
}

// Guards against a race where several concurrent requests each see an empty
// table and all try to insert the same defaults (unique constraint crash).
let seedPromise: Promise<void> | null = null;

function seedDefaultsIfEmpty(): Promise<void> {
  if (!seedPromise) seedPromise = doSeedDefaultsIfEmpty();
  return seedPromise;
}

async function doSeedDefaultsIfEmpty() {
  const count = await prisma.riskQuestion.count();
  if (count > 0) return;

  const yesNoOptions = JSON.stringify([
    { label: "No", points: 0 },
    { label: "Yes", points: 1 },
  ]);

  await prisma.riskQuestion.createMany({
    data: [
      ...DIMENSION_1_DEFAULTS.map((q, i) => ({
        key: q.key,
        dimension: 1,
        order: i + 1,
        text: q.text,
        helpText: q.helpText,
        options: yesNoOptions,
      })),
      ...DIMENSION_2_DEFAULTS.map((q, i) => ({
        key: q.key,
        dimension: 2,
        order: i + 1,
        text: q.text,
        helpText: q.helpText,
        options: JSON.stringify(q.options),
      })),
    ],
  });
}

// Active questions only, in display order — what the live intake/assessment
// UI shows.
export async function getActiveRiskQuestions(): Promise<Question[]> {
  await seedDefaultsIfEmpty();
  const rows = await prisma.riskQuestion.findMany({
    where: { isActive: true },
    orderBy: [{ dimension: "asc" }, { order: "asc" }],
  });
  return rows.map(toWireQuestion);
}

// Every question, including inactive — for admin management and for
// re-hydrating an older finalized assessment's report if it predates
// snapshotting.
export async function getAllRiskQuestions(): Promise<Question[]> {
  await seedDefaultsIfEmpty();
  const rows = await prisma.riskQuestion.findMany({ orderBy: [{ dimension: "asc" }, { order: "asc" }] });
  return rows.map(toWireQuestion);
}

// Dimension 2 total only (sums each answered question's chosen option points).
export function computeScore(answers: Record<string, string>, dimension2Questions: Question[]): number {
  let total = 0;
  for (const q of dimension2Questions) {
    const chosenLabel = answers[q.id];
    const option = q.options.find((o) => o.label === chosenLabel);
    if (option) total += option.points;
  }
  return total;
}

// Dimension 1: true if any trigger question's chosen option has points > 0.
export function computeReviewTriggered(answers: Record<string, string>, dimension1Questions: Question[]): boolean {
  return dimension1Questions.some((q) => {
    const chosenLabel = answers[q.id];
    const option = q.options.find((o) => o.label === chosenLabel);
    return !!option && option.points > 0;
  });
}
