// AUTO-GENERATED from the reference AI Work Paper Generator tool.
// Question text and citations are genericized (org name, internal doc refs) but the
// substantive regulatory citations (GLBA, ECOA, BSA, OFAC, GDPR, CCPA, etc.) are kept as-is.

export type ReviewFunctionKey = "INFOSEC" | "MRM" | "COMPLIANCE" | "FIU" | "PRIVACY";

export interface WorkPaperQuestion {
  id: string;
  text: string;
  citation: string;
}

export interface WorkPaperSection {
  id: string;
  title: string;
  triggerLabel: string;
  triggers: { deliveryModels: number[]; capabilityTiers: number[]; riskFactors: number[] };
  questions: WorkPaperQuestion[];
}

export interface ReviewFunctionDef {
  key: ReviewFunctionKey;
  label: string;
  sections: WorkPaperSection[];
}

export const REVIEW_FUNCTIONS: Record<ReviewFunctionKey, ReviewFunctionDef> = {
  INFOSEC: {
    key: "INFOSEC",
    label: "Information Security",
    sections: [
      {
        id: "infosec_arch",
        title: "Architecture, Integration, and Network Security",
        triggerLabel: "All D/T. Always in scope.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_arch_0", text: "Does the AI capability introduce new APIs, service endpoints, or webhooks?", citation: "IR 8596 ID.AM; FFIEC Architecture; CRI GV.SP-02" },
          { id: "infosec_arch_1", text: "Does the AI require service accounts, privileged access, IAM roles, or API keys?", citation: "IR 8596 PR.AA; FFIEC Access Controls; CRI PR.AC-04" },
          { id: "infosec_arch_2", text: "Does the AI connect to internal databases, data warehouses, or core banking systems?", citation: "AI RMF Map 1.1; IR 8596 ID.AM; FFIEC Architecture" },
          { id: "infosec_arch_3", text: "Does the AI communicate with external services or third-party inference APIs?", citation: "AI RMF Map 3.1; TPRM Guidance; CRI ID.SC-01" },
          { id: "infosec_arch_4", text: "Is the AI hosted in a dedicated, segmented environment?", citation: "IR 8596 PR.DS; FFIEC Architecture; CRI PR.AC-05" },
          { id: "infosec_arch_5", text: "Is the hosting environment documented with architecture and data flow diagrams?", citation: "AI RMF Govern 1.4; IR 8596 ID.AM" },
          { id: "infosec_arch_6", text: "Are container security controls in place if containerized workloads are used?", citation: "IR 8596 PR.PS; CRI PR.IP-03" },
          { id: "infosec_arch_7", text: "Has a threat model been developed or updated for this AI implementation?", citation: "AI RMF Map 2.1; AI 600-1 Map 2.1; CRI ID.RA-01" },
          { id: "infosec_arch_8", text: "Are all integration points authenticated with mutual TLS, OAuth 2.0, or equivalent?", citation: "IR 8596 PR.DS; CRI PR.DS-02" },
          { id: "infosec_arch_9", text: "Are API rate limiting and throttling controls implemented?", citation: "IR 8596 PR.DS; OWASP-LLM #10" },
        ],
      },
      {
        id: "infosec_data",
        title: "Data Security, Privacy, and Classification",
        triggerLabel: "All D/T. Always in scope.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_data_0", text: "Does the AI process, store, transmit, or access PII?", citation: "GLBA §501; IR 8596 PR.DS; CRI PR.DS-01" },
          { id: "infosec_data_1", text: "Does the AI process, store, transmit, or access PCI data?", citation: "PCI DSS 3.4/4.1; CRI PR.DS-01" },
          { id: "infosec_data_2", text: "Does the AI process, store, transmit, or access NPI as defined under GLBA?", citation: "GLBA §501; Reg P; CRI PR.DS-01" },
          { id: "infosec_data_3", text: "Is all data encrypted in transit using TLS 1.2 or higher?", citation: "IR 8596 PR.DS; FFIEC Encryption; CRI PR.DS-02" },
          { id: "infosec_data_4", text: "Is all data encrypted at rest using AES-256 or equivalent?", citation: "IR 8596 PR.DS; CRI PR.DS-01" },
          { id: "infosec_data_5", text: "Does the vendor/platform log, store, or retain prompts or AI interactions?", citation: "AI 600-1 Manage 2.2; CRI PR.DS-05; GLBA" },
          { id: "infosec_data_6", text: "Can the organization opt out of prompt logging or training data contribution?", citation: "AI 600-1 Govern 1.3; CRI GV.PO-01" },
          { id: "infosec_data_7", text: "Are DLP controls implemented to prevent sensitive data in AI prompts?", citation: "IR 8596 PR.DS; OWASP-LLM #6; CRI PR.DS-05" },
          { id: "infosec_data_8", text: "Are tenant isolation or logical separation controls confirmed?", citation: "IR 8596 PR.DS; TPRM Guidance; CRI PR.AC-05" },
          { id: "infosec_data_9", text: "Does the AI use customer or organization data for model training?", citation: "AI 600-1 Govern 1.6; OWASP-LLM #3" },
        ],
      },
      {
        id: "infosec_iam",
        title: "Identity, Access Management, and Privilege Controls",
        triggerLabel: "All D/T. Always in scope.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_iam_0", text: "Is access governed by the organization's enterprise IAM solution (SSO, MFA)?", citation: "IR 8596 PR.AA; CRI PR.AC-01" },
          { id: "infosec_iam_1", text: "Is MFA required for all users accessing the AI capability?", citation: "IR 8596 PR.AA; CRI PR.AC-07" },
          { id: "infosec_iam_2", text: "Are RBAC controls implemented with least-privilege principles?", citation: "IR 8596 PR.AA; CRI PR.AC-04; OWASP-LLM #8" },
          { id: "infosec_iam_3", text: "If service accounts or API keys are used, are they rotated and stored in a secrets vault?", citation: "IR 8596 PR.AA; OWASP-LLM #7" },
          { id: "infosec_iam_4", text: "Are administrative actions subject to separation of duties?", citation: "FFIEC Management; CRI PR.AC-04" },
          { id: "infosec_iam_5", text: "Is user access reviewed through existing access certification processes?", citation: "IR 8596 PR.AA; CRI PR.AC-01" },
          { id: "infosec_iam_6", text: "Are session management controls enforced?", citation: "IR 8596 PR.AA; CRI PR.AC-07" },
        ],
      },
      {
        id: "infosec_prompt",
        title: "AI-Specific: Prompt Security and Input Controls",
        triggerLabel: "All tiers. Always in scope.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_prompt_0", text: "Are protections in place to detect and prevent direct prompt injection?", citation: "AI 600-1 Measure 2.6; OWASP-LLM #1; CRI MS.MN-03" },
          { id: "infosec_prompt_1", text: "Are protections in place against indirect prompt injection (via retrieved data)?", citation: "AI 600-1 Measure 2.6; OWASP-LLM #1" },
          { id: "infosec_prompt_2", text: "Are system prompts protected against extraction or disclosure?", citation: "OWASP-LLM #7; CRI PR.DS-05" },
          { id: "infosec_prompt_3", text: "Is input validation/sanitization performed before content reaches the model?", citation: "OWASP-LLM #1; IR 8596 PR.DS" },
          { id: "infosec_prompt_4", text: "Are there controls to prevent execution of instructions embedded in retrieved data?", citation: "OWASP-LLM #1; AI 600-1 Measure 2.6" },
        ],
      },
      {
        id: "infosec_output",
        title: "AI-Specific: Output Safety and Data Leakage Prevention",
        triggerLabel: "All tiers.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_output_0", text: "Are output guardrails implemented to prevent sensitive or policy-violating content?", citation: "AI 600-1 Measure 2.7; OWASP-LLM #6; CRI MS.MN-04" },
          { id: "infosec_output_1", text: "Are controls in place to detect and redact PII/NPI/PCI in outputs?", citation: "GLBA; OWASP-LLM #6; CRI PR.DS-05" },
          { id: "infosec_output_2", text: "Is output validated before acting upon it in high-consequence workflows?", citation: "AI RMF Measure 2.8; OWASP-LLM #9" },
          { id: "infosec_output_3", text: "Are controls in place to prevent hallucinated information in critical processes?", citation: "AI 600-1 Confabulation; OWASP-LLM #9" },
          { id: "infosec_output_4", text: "Are AI-generated outputs logged and auditable?", citation: "IR 8596 DE.CM; AI RMF Manage 2.2; CRI DE.AE-01" },
        ],
      },
      {
        id: "infosec_model",
        title: "AI-Specific: Model Integrity and Supply Chain",
        triggerLabel: "T3 or T4.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [3,4], riskFactors: [] },
        questions: [
          { id: "infosec_model_0", text: "Are controls in place to mitigate model inversion or data extraction?", citation: "AI 600-1 Measure 2.5; OWASP-LLM #6" },
          { id: "infosec_model_1", text: "Are AI dependencies and upstream providers documented and reviewed?", citation: "AI RMF Map 3.1; OWASP-LLM #5; CRI ID.SC-01" },
          { id: "infosec_model_2", text: "Is the model supply chain documented?", citation: "OWASP-LLM #5; AI 600-1 Map 1.5; CRI ID.SC-02" },
          { id: "infosec_model_3", text: "Are model artifacts protected against unauthorized modification?", citation: "IR 8596 PR.DS; OWASP-LLM #5" },
          { id: "infosec_model_4", text: "Is model versioning tracked with rollback procedures?", citation: "AI RMF Manage 2.4; SR 11-7; CRI MG.MG-02" },
        ],
      },
      {
        id: "infosec_agent",
        title: "AI-Specific: Agentic AI Controls",
        triggerLabel: "T4 only, or RF5 / RF8.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [4], riskFactors: [5,8] },
        questions: [
          { id: "infosec_agent_0", text: "Are the agent's permitted actions explicitly defined and bounded?", citation: "OWASP-Agent #1; AI 600-1 Govern 1.5" },
          { id: "infosec_agent_1", text: "Are least-privilege principles enforced for all tools/APIs the agent can access?", citation: "OWASP-Agent #1; CRI PR.AC-04" },
          { id: "infosec_agent_2", text: "Is human-in-the-loop approval required for high-consequence actions?", citation: "OWASP-Agent #9; CRI GV.OC-01" },
          { id: "infosec_agent_3", text: "Are there guardrails to prevent excessive autonomy beyond intended scope?", citation: "OWASP-Agent #1; OWASP-LLM #8" },
          { id: "infosec_agent_4", text: "If multi-agent, are inter-agent communications authenticated and validated?", citation: "OWASP-Agent #7; CRI PR.AC-05" },
          { id: "infosec_agent_5", text: "Are controls in place to detect cascading failures?", citation: "OWASP-Agent #8; CRI RS.AN-01" },
          { id: "infosec_agent_6", text: "Is persistent memory/context protected against poisoning?", citation: "OWASP-Agent #6; CRI PR.DS-05" },
          { id: "infosec_agent_7", text: "Are agent decisions and actions logged for forensic reconstruction?", citation: "OWASP-Agent #3; CRI DE.AE-01" },
          { id: "infosec_agent_8", text: "Is there an emergency shutoff / circuit-breaker mechanism?", citation: "OWASP-Agent #1; CRI RS.RP-01" },
        ],
      },
      {
        id: "infosec_rag",
        title: "RAG, Knowledge Retrieval, and Data Source Security",
        triggerLabel: "T3 or T4 with retrieval.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [3,4], riskFactors: [] },
        questions: [
          { id: "infosec_rag_0", text: "Are document repos/knowledge bases subject to access controls?", citation: "IR 8596 PR.AA; CRI PR.AC-04" },
          { id: "infosec_rag_1", text: "Are vector databases protected with authentication, encryption, and access logging?", citation: "IR 8596 PR.DS; CRI PR.DS-01" },
          { id: "infosec_rag_2", text: "Are controls in place to prevent cross-authorization leakage via retrieval?", citation: "OWASP-LLM #6; CRI PR.AC-04" },
          { id: "infosec_rag_3", text: "Is ingested document integrity verified?", citation: "OWASP-LLM #3; CRI PR.DS-06" },
          { id: "infosec_rag_4", text: "Is citation/source attribution validated for accuracy?", citation: "AI 600-1 Confabulation; CRI MS.MN-04" },
        ],
      },
      {
        id: "infosec_infra",
        title: "Infrastructure Security and Operational Controls",
        triggerLabel: "Always in scope.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_infra_0", text: "Is the AI environment included in vulnerability scanning?", citation: "IR 8596 ID.RA; CRI ID.RA-01" },
          { id: "infosec_infra_1", text: "Is patch management performed on a defined cadence?", citation: "IR 8596 PR.PS; CRI PR.IP-12" },
          { id: "infosec_infra_2", text: "Are security logs forwarded to the organization's SIEM?", citation: "IR 8596 DE.CM; CRI DE.CM-01" },
          { id: "infosec_infra_3", text: "Are security alerts/anomalies monitored by the SOC?", citation: "IR 8596 DE.AE; CRI DE.AE-01" },
          { id: "infosec_infra_4", text: "Is the AI included in BC/DR planning?", citation: "IR 8596 RC.RP; CRI RC.RP-01" },
          { id: "infosec_infra_5", text: "Is the AI environment subject to config management and drift detection?", citation: "IR 8596 PR.PS; CRI PR.IP-01" },
        ],
      },
      {
        id: "infosec_monitor",
        title: "Monitoring, Anomaly Detection, and Incident Response",
        triggerLabel: "T2/T3/T4.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_monitor_0", text: "Are monitoring controls in place to detect anomalous or unauthorized AI usage?", citation: "IR 8596 DE.CM; CRI DE.CM-01" },
          { id: "infosec_monitor_1", text: "Is model drift or anomalous AI behavior monitored?", citation: "AI RMF Measure 3.2; SR 11-7" },
          { id: "infosec_monitor_2", text: "Is there an AI-specific incident response plan?", citation: "IR 8596 RS.RP; CRI RS.RP-01" },
          { id: "infosec_monitor_3", text: "Are there defined escalation procedures for harmful outputs?", citation: "AI RMF Manage 2.4; CRI RS.AN-01" },
          { id: "infosec_monitor_4", text: "Is there a process for rapidly disabling or rolling back the AI?", citation: "AI RMF Manage 2.4; CRI RS.RP-01" },
        ],
      },
      {
        id: "infosec_vendor",
        title: "Vendor / Third-Party AI Provider Security Posture",
        triggerLabel: "Any vendor scenario (D1, D2, or D3).",
        triggers: { deliveryModels: [1,2,3], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_vendor_0", text: "Has the vendor provided a current SOC 2 Type II report?", citation: "TPRM Guidance; CRI ID.SC-04" },
          { id: "infosec_vendor_1", text: "Has the vendor provided a penetration test summary?", citation: "TPRM Guidance; CRI ID.SC-04" },
          { id: "infosec_vendor_2", text: "Does the vendor commit to not using organization data for model training?", citation: "AI 600-1 Govern 1.6; CRI GV.PO-01" },
          { id: "infosec_vendor_3", text: "Does the vendor provide transparency on base model(s) and provenance?", citation: "OWASP-LLM #5; CRI ID.SC-02" },
          { id: "infosec_vendor_4", text: "Does the vendor have an AI-specific incident notification process?", citation: "TPRM Guidance; CRI RS.CO-02" },
          { id: "infosec_vendor_5", text: "Is there a right-to-audit or right-to-test clause?", citation: "TPRM Guidance; CRI ID.SC-04" },
          { id: "infosec_vendor_6", text: "Does the vendor commit to defined uptime/availability SLAs?", citation: "TPRM Guidance; CRI RC.RP-01" },
        ],
      },
      {
        id: "infosec_testing",
        title: "Security Testing Results",
        triggerLabel: "All use cases.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "infosec_testing_0", text: "Has penetration testing been conducted against the AI implementation?", citation: "IR 8596 ID.RA; CRI ID.RA-01" },
          { id: "infosec_testing_1", text: "Has prompt injection testing been conducted?", citation: "OWASP-LLM #1; AI 600-1 Measure 2.6" },
          { id: "infosec_testing_2", text: "Have test results been reviewed and remediation tracked?", citation: "IR 8596 RS.AN; CRI RS.AN-01" },
        ],
      },
    ],
  },
  MRM: {
    key: "MRM",
    label: "Model Risk Management",
    sections: [
      {
        id: "mrm_outcome",
        title: "Outcome Reasonableness and Reliability",
        triggerLabel: "All tiers.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_outcome_0", text: "Are the AI's outputs reasonable, consistent, and appropriate for the stated intended use?", citation: "SR 11-7 Outcomes Analysis; CRI MS.AS-01" },
          { id: "mrm_outcome_1", text: "Has the model owner defined quantitative and/or qualitative performance metrics?", citation: "SR 11-7; OCC MRM HB; CRI MS.AS-02" },
          { id: "mrm_outcome_2", text: "Have outputs been tested against known-good benchmarks or expert judgment?", citation: "SR 11-7; AI RMF Measure 2.6" },
          { id: "mrm_outcome_3", text: "Is output consistency measured across repeated runs with similar inputs?", citation: "AI 600-1 Confabulation; CRI MS.AS-01" },
          { id: "mrm_outcome_4", text: "Are hallucination or confabulation rates measured and within acceptable thresholds?", citation: "AI 600-1; OWASP-LLM #9" },
          { id: "mrm_outcome_5", text: "Has performance been evaluated under stress conditions and adversarial inputs?", citation: "SR 11-7 Sensitivity Analysis; CRI MS.AS-05" },
          { id: "mrm_outcome_6", text: "For T3: Is retrieval accuracy measured? Are responses grounded in source documents?", citation: "AI 600-1 Map 2.3" },
          { id: "mrm_outcome_7", text: "For T4: Are end-to-end task completion rates measured?", citation: "AI RMF Measure 2.8" },
        ],
      },
      {
        id: "mrm_conceptual",
        title: "Conceptual Soundness",
        triggerLabel: "All tiers.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_conceptual_0", text: "Is the AI approach appropriate for the business problem?", citation: "SR 11-7 Conceptual Soundness; CRI GV.MT-01" },
          { id: "mrm_conceptual_1", text: "Are the model's assumptions, limitations, and known failure modes documented?", citation: "SR 11-7 Documentation; AI RMF Map 1.1" },
          { id: "mrm_conceptual_2", text: "For vendor LLMs: Are limitations of interpretability documented?", citation: "SR 11-7; AI 600-1 Govern 1.4" },
          { id: "mrm_conceptual_3", text: "Are compensating controls documented where conceptual soundness analysis is not possible?", citation: "SR 11-7 Validation; OCC MRM HB" },
          { id: "mrm_conceptual_4", text: "For RAG: Is the retrieval strategy appropriate?", citation: "AI RMF Map 1.5" },
          { id: "mrm_conceptual_5", text: "For agentic: Is the agent's architecture and harness design sound?", citation: "AI RMF Map 1.1; OWASP-Agent #1" },
          { id: "mrm_conceptual_6", text: "For hybrid systems: Is the interaction between traditional and AI components well-defined and logically sound?", citation: "SR 11-7 Validation; CRI GV.MT-01" },
          { id: "mrm_conceptual_7", text: "Has the model owner assessed alternative approaches?", citation: "SR 11-7 Conceptual Soundness" },
        ],
      },
      {
        id: "mrm_datamrm",
        title: "Data Integrity and Privacy",
        triggerLabel: "All tiers.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_datamrm_0", text: "Is the data used by the AI appropriate and of sufficient quality?", citation: "SR 11-7 Data Quality; AI RMF Map 5.1" },
          { id: "mrm_datamrm_1", text: "Is data classification documented for all data the AI processes?", citation: "GLBA; CRI MP.DQ-02" },
          { id: "mrm_datamrm_2", text: "Is data lineage documented from source through AI processing to output?", citation: "AI RMF Map 1.5; CRI MP.DQ-03" },
          { id: "mrm_datamrm_3", text: "For vendor models: Is training data provenance available?", citation: "AI 600-1 Map 1.5; OWASP-LLM #3" },
          { id: "mrm_datamrm_4", text: "For custom models (D4): Is training data documented with fitness-for-purpose assessment?", citation: "SR 11-7 Documentation" },
          { id: "mrm_datamrm_5", text: "Are data minimization principles applied?", citation: "GLBA; AI RMF Map 5.1" },
          { id: "mrm_datamrm_6", text: "Is data encrypted in transit and at rest?", citation: "InfoSec Review coordination; CRI PR.DS-02" },
          { id: "mrm_datamrm_7", text: "Does the AI vendor use organization data for model training?", citation: "AI 600-1 Govern 1.6" },
          { id: "mrm_datamrm_8", text: "For RAG systems: Are document access controls consistent with the organization's data classification policy?", citation: "CRI PR.AC-04; InfoSec Review coordination" },
          { id: "mrm_datamrm_9", text: "Is a Privacy Impact Assessment required and completed (coordinated with Privacy)?", citation: "GLBA; CRI GV.PO-01" },
        ],
      },
      {
        id: "mrm_bias",
        title: "Bias and Fairness",
        triggerLabel: "Required if RF2 or RF10.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [2,10] },
        questions: [
          { id: "mrm_bias_0", text: "Has a bias risk assessment been conducted for this use case?", citation: "AI RMF Map 2.3; CRI MS.BI-01; ECOA" },
          { id: "mrm_bias_1", text: "Are outputs tested for disparate impact across protected classes?", citation: "ECOA; FCRA; SR 11-7" },
          { id: "mrm_bias_2", text: "Is there a process for generating model-specific adverse action explanations?", citation: "ECOA; Reg B §1002.9; FCRA §615" },
          { id: "mrm_bias_3", text: "Are proxy variables assessed for discriminatory correlation?", citation: "AI RMF Measure 2.11; ECOA" },
          { id: "mrm_bias_4", text: "Is bias monitoring included in the OMP?", citation: "SR 11-7 Ongoing Monitoring" },
          { id: "mrm_bias_5", text: "Has the model owner documented fairness criteria and testing methodology?", citation: "AI RMF Measure 2.11" },
          { id: "mrm_bias_6", text: "For customer-facing systems (RF2): Has the AI been tested for demographic bias in its responses and recommendations?", citation: "AI 600-1 Homogenization risk; CRI MS.BI-02" },
          { id: "mrm_bias_7", text: "For regulatory-sensitive use cases (RF10): Has fair lending / fair treatment testing been conducted at a level commensurate with examiner expectations?", citation: "ECOA; FCRA; SR 11-7; CRI MS.BI-02; OCC MRM HB" },
        ],
      },
      {
        id: "mrm_secmrm",
        title: "Security and Misuse",
        triggerLabel: "All tiers. Coordinated with InfoSec.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_secmrm_0", text: "Has the InfoSec cybersecurity review been completed?", citation: "InfoSec Executive Summary" },
          { id: "mrm_secmrm_1", text: "What is the composite cybersecurity risk rating from InfoSec?", citation: "InfoSec Executive Summary" },
          { id: "mrm_secmrm_2", text: "Are InfoSec conditions reflected in this validation's conditions?", citation: "SR 11-7 Governance" },
          { id: "mrm_secmrm_3", text: "Is the AI resilient to prompt injection commensurate with its risk profile?", citation: "AI 600-1 Measure 2.6; OWASP-LLM #1" },
          { id: "mrm_secmrm_4", text: "Are output guardrails sufficient for production?", citation: "AI 600-1 Measure 2.7" },
          { id: "mrm_secmrm_5", text: "Is the model's supply chain documented and assessed?", citation: "OWASP-LLM #5" },
          { id: "mrm_secmrm_6", text: "Are access controls and authentication mechanisms appropriate for the model's sensitivity?", citation: "InfoSec coordination; CRI PR.AC-01" },
          { id: "mrm_secmrm_7", text: "Is there an AI-specific incident response plan or has the existing plan been updated?", citation: "CRI RS.RP-01; InfoSec coordination" },
        ],
      },
      {
        id: "mrm_control",
        title: "Control Effectiveness",
        triggerLabel: "T2/T3/T4.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_control_0", text: "Are guardrails documented and functioning as designed?", citation: "AI RMF Manage 2.2; OWASP-LLM #8" },
          { id: "mrm_control_1", text: "Are guardrails tested for bypass resistance under adversarial conditions?", citation: "AI 600-1 Measure 2.6; OWASP-LLM #1" },
          { id: "mrm_control_2", text: "For T2: Are AI outputs appropriately bounded within the defined workflow?", citation: "SR 11-7 Implementation" },
          { id: "mrm_control_3", text: "For T3: Are retrieval access controls enforced?", citation: "CRI PR.AC-04; OWASP-LLM #6" },
          { id: "mrm_control_4", text: "For RAG systems: Is output grounding validated § does the AI accurately cite and attribute retrieved sources?", citation: "AI 600-1 Confabulation; CRI MS.AS-04" },
          { id: "mrm_control_5", text: "Where HITL is required: Is human review substantive or perfunctory?", citation: "AI RMF Govern 1.5; OWASP-Agent #9" },
          { id: "mrm_control_6", text: "Are escalation triggers defined and functioning?", citation: "AI RMF Manage 2.4" },
          { id: "mrm_control_7", text: "Is the control architecture documented with clear accountabilities for each control layer?", citation: "SR 11-7 Governance; CRI GV.OC-03" },
        ],
      },
      {
        id: "mrm_harness",
        title: "Harness Engineering Assessment",
        triggerLabel: "T4, RF5, or RF8.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [4], riskFactors: [5,8] },
        questions: [
          { id: "mrm_harness_0", text: "Is the context architecture documented § what information does the agent see at each step?", citation: "AI RMF Map 1.1; OWASP-Agent #6" },
          { id: "mrm_harness_1", text: "Is the agent's context bounded so it operates within defined information boundaries?", citation: "OWASP-Agent #1" },
          { id: "mrm_harness_2", text: "Are system prompts and instructions structured to minimize ambiguity?", citation: "AI 600-1 Govern 1.5" },
          { id: "mrm_harness_3", text: "Are permitted actions bounded by allowlists? Prohibited actions by denylists?", citation: "OWASP-Agent #1" },
          { id: "mrm_harness_4", text: "Are structural boundaries enforced through automated checks, not just policy?", citation: "OWASP-Agent #1" },
          { id: "mrm_harness_5", text: "Is least-privilege enforced for all tools, APIs, and data sources?", citation: "OWASP-Agent #1; CRI PR.AC-04" },
          { id: "mrm_harness_6", text: "Can the agent modify its own permissions or override guardrails?", citation: "OWASP-Agent #10" },
          { id: "mrm_harness_7", text: "Are verification systems in place that continuously evaluate agent outputs?", citation: "AI RMF Measure 3.2" },
          { id: "mrm_harness_8", text: "Do verification systems assess outcome accomplishment rather than process compliance?", citation: "AI RMF Measure 2.8" },
          { id: "mrm_harness_9", text: "Is the circuit-breaker / emergency shutoff mechanism tested and functional?", citation: "OWASP-Agent #1; CRI RS.RP-01" },
          { id: "mrm_harness_10", text: "Is every agent failure treated as a signal to improve the harness?", citation: "AI RMF Manage 4.1" },
          { id: "mrm_harness_11", text: "Is there a documented process for incorporating failure patterns into the harness?", citation: "AI RMF Manage 4.1" },
          { id: "mrm_harness_12", text: "Are feedback loops operating at a frequency commensurate with deployment velocity?", citation: "AI RMF Manage 4.1" },
          { id: "mrm_harness_13", text: "For multi-agent: Are inter-agent communications authenticated?", citation: "OWASP-Agent #7, #8" },
          { id: "mrm_harness_14", text: "Are all agent prompts, tool calls, data accessed, actions taken, and approvals logged?", citation: "SR 11-7 Documentation; OWASP-Agent #3" },
          { id: "mrm_harness_15", text: "Are logs retained per the organization's retention policy?", citation: "CRI DE.AE-01" },
          { id: "mrm_harness_16", text: "Are log formats suitable for automated analysis and anomaly detection?", citation: "CRI DE.CM-01" },
        ],
      },
      {
        id: "mrm_impl",
        title: "Implementation Integrity",
        triggerLabel: "All tiers.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_impl_0", text: "Is the AI system deployed in accordance with the approved design and documentation?", citation: "SR 11-7 Implementation" },
          { id: "mrm_impl_1", text: "Are change controls in place per the the organization's AI Model Risk Standard?", citation: "SR 11-7 Change Management" },
          { id: "mrm_impl_2", text: "Are the boundaries of 'routine changes' explicitly defined and approved?", citation: "AI-Specific MRM Standard §5.5" },
          { id: "mrm_impl_3", text: "Is access to the AI's configuration, prompts, guardrails, and tools controlled?", citation: "SR 11-7 Governance; CRI PR.AC-04" },
          { id: "mrm_impl_4", text: "Is model versioning tracked with rollback procedures?", citation: "AI RMF Manage 2.4; SR 11-7" },
          { id: "mrm_impl_5", text: "Is the deployment environment consistent with the tested environment?", citation: "SR 11-7 Implementation" },
          { id: "mrm_impl_6", text: "For vendor AI: Is the vendor's change notification process documented?", citation: "TPRM Guidance" },
          { id: "mrm_impl_7", text: "Is the OMP drafted and ready for approval within 90 days?", citation: "SR 11-7" },
        ],
      },
      {
        id: "mrm_omp",
        title: "Ongoing Monitoring Plan Assessment",
        triggerLabel: "All review types.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [] },
        questions: [
          { id: "mrm_omp_0", text: "Has the model owner proposed an Ongoing Monitoring Plan?", citation: "SR 11-7 Ongoing Monitoring" },
          { id: "mrm_omp_1", text: "Does the OMP include performance metrics appropriate to the capability tier?", citation: "SR 11-7" },
          { id: "mrm_omp_2", text: "Does the OMP include drift detection and alerting?", citation: "SR 11-7" },
          { id: "mrm_omp_3", text: "For T2+: Does the OMP include control effectiveness monitoring?", citation: "AI-Specific MRM Standard §9; CRI MG.MG-01" },
          { id: "mrm_omp_4", text: "For T3: Does the OMP include retrieval accuracy monitoring and source fidelity verification?", citation: "AI-Specific MRM Standard §9; CRI MS.AS-04" },
          { id: "mrm_omp_5", text: "For T4: Does the OMP include action audit volume, failure rates, and harness feedback cadence?", citation: "AI-Specific MRM Standard §9" },
          { id: "mrm_omp_6", text: "For RF2/RF10: Does the OMP include bias/fairness monitoring?", citation: "ECOA; CRI MS.BI-04" },
          { id: "mrm_omp_7", text: "Is monitoring frequency commensurate with the model's risk tier?", citation: "SR 11-7; OCC Bulletin 2025-26" },
          { id: "mrm_omp_8", text: "Are escalation thresholds defined?", citation: "SR 11-7" },
          { id: "mrm_omp_9", text: "Is the OMP ready for approval within 90 days of production deployment?", citation: "AI-Specific MRM Standard §10; CRI MG.MG-01" },
        ],
      },
    ],
  },
  COMPLIANCE: {
    key: "COMPLIANCE",
    label: "Enterprise Compliance",
    sections: [
      {
        id: "compliance_fairlend",
        title: "Fair Lending (ECOA / Reg B / FCRA)",
        triggerLabel: "RF2 + RF10 + credit decisioning.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [2,10] },
        questions: [
          { id: "compliance_fairlend_0", text: "Does the AI's output materially influence credit decisions, pricing, terms, or availability?", citation: "ECOA §701; Reg B §1002.2; SR 11-7" },
          { id: "compliance_fairlend_1", text: "Has disparate impact testing been conducted across all protected classes?", citation: "ECOA; Reg B §1002.4" },
          { id: "compliance_fairlend_2", text: "Can the AI produce specific, behavioral adverse action reasons for individual applicants?", citation: "FCRA §615; Reg B §1002.9; CFPB Circular 2022-03" },
          { id: "compliance_fairlend_3", text: "Are proxy variables and alternative data sources assessed for discriminatory correlation?", citation: "ECOA; CFPB guidance" },
          { id: "compliance_fairlend_4", text: "Is fair lending testing methodology documented and repeatable?", citation: "ECOA; SR 11-7" },
          { id: "compliance_fairlend_5", text: "Has MRM independently validated the bias testing results?", citation: "SR 11-7" },
          { id: "compliance_fairlend_6", text: "Is fair lending monitoring included in the ongoing monitoring plan?", citation: "ECOA; CRI MS.BI-04" },
        ],
      },
      {
        id: "compliance_udaap",
        title: "UDAAP / UDAP",
        triggerLabel: "RF2 (customer-facing).",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [2] },
        questions: [
          { id: "compliance_udaap_0", text: "Could the AI's outputs be perceived as unfair to consumers?", citation: "Dodd-Frank §1036; FTC Act §5" },
          { id: "compliance_udaap_1", text: "Could the AI produce deceptive outputs (misleading representations, material omissions)?", citation: "Dodd-Frank §1036; FTC Act §5" },
          { id: "compliance_udaap_2", text: "Could the AI engage in abusive practices?", citation: "Dodd-Frank §1036(d)" },
          { id: "compliance_udaap_3", text: "If customer-facing: Are disclosures provided that the customer is interacting with AI?", citation: "CFPB guidance; state AI transparency" },
          { id: "compliance_udaap_4", text: "Are guardrails in place to prevent unauthorized promises, commitments, or guarantees?", citation: "UDAAP; CRI MS.MN-04" },
          { id: "compliance_udaap_5", text: "Is there a complaint escalation pathway for AI-generated communications or decisions?", citation: "Dodd-Frank; CFPB" },
        ],
      },
      {
        id: "compliance_disclosures",
        title: "Regulatory Disclosures (Reg Z / DD / E)",
        triggerLabel: "AI generates regulated disclosures + RF2.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [2,3,4], riskFactors: [2] },
        questions: [
          { id: "compliance_disclosures_0", text: "Does the AI generate, modify, or personalize content subject to Reg Z?", citation: "TILA; Reg Z §1026.17-18" },
          { id: "compliance_disclosures_1", text: "Does the AI generate content subject to Reg DD?", citation: "TISA; Reg DD §1030.4" },
          { id: "compliance_disclosures_2", text: "Does the AI generate content subject to Reg E?", citation: "EFTA; Reg E §1005.7" },
          { id: "compliance_disclosures_3", text: "Are AI-generated disclosures reviewed by Compliance before deployment?", citation: "All applicable Regs" },
          { id: "compliance_disclosures_4", text: "Are disclosures tested for completeness, accuracy, and timeliness?", citation: "Reg Z; Reg DD; Reg E" },
        ],
      },
      {
        id: "compliance_stateai",
        title: "State AI Laws",
        triggerLabel: "RF2 in states with AI legislation.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [2] },
        questions: [
          { id: "compliance_stateai_0", text: "Has a jurisdictional analysis identified applicable state AI laws?", citation: "State AI legislation" },
          { id: "compliance_stateai_1", text: "If Colorado AI Act applies: Does the AI make 'consequential decisions' about consumers?", citation: "Colorado AI Act C.R.S. §6-1-1701" },
          { id: "compliance_stateai_2", text: "Are required impact assessments completed for high-risk AI systems?", citation: "State AI legislation" },
          { id: "compliance_stateai_3", text: "Are required consumer notifications in place per applicable state requirements?", citation: "State AI legislation" },
          { id: "compliance_stateai_4", text: "Is there a process to monitor new state AI laws?", citation: "CRI GV.PO-01" },
        ],
      },
      {
        id: "compliance_marketing",
        title: "Advertising and Marketing Compliance",
        triggerLabel: "RF2 + AI generates marketing content.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [2,3,4], riskFactors: [2] },
        questions: [
          { id: "compliance_marketing_0", text: "Does the AI generate, personalize, or target marketing content?", citation: "Reg Z §1026.24; Reg DD; CAN-SPAM" },
          { id: "compliance_marketing_1", text: "Are required disclosures included in AI-generated marketing materials?", citation: "Reg Z trigger terms; FDIC advertising" },
          { id: "compliance_marketing_2", text: "Are controls in place to prevent misleading or noncompliant marketing claims?", citation: "UDAAP; FTC Act §5" },
          { id: "compliance_marketing_3", text: "Is AI-generated marketing content subject to pre-deployment Compliance review?", citation: "organization marketing program" },
          { id: "compliance_marketing_4", text: "Are AI targeting decisions assessed for fair lending implications?", citation: "ECOA; Fair Housing Act" },
        ],
      },
    ],
  },
  FIU: {
    key: "FIU",
    label: "Financial Intelligence Unit",
    sections: [
      {
        id: "fiu_txnmon",
        title: "BSA/AML: Transaction Monitoring",
        triggerLabel: "RF10. AI used in transaction monitoring.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [10] },
        questions: [
          { id: "fiu_txnmon_0", text: "Does the AI produce alerts, scores, or risk indicators used in BSA/AML monitoring?", citation: "BSA §5318; FinCEN guidance; SR 21-8" },
          { id: "fiu_txnmon_1", text: "Are alert thresholds, rules, or scoring criteria documented and validated?", citation: "SR 11-7; FinCEN guidance; SR 21-8" },
          { id: "fiu_txnmon_2", text: "Has the AI's false positive rate been assessed?", citation: "SR 11-7; FinCEN guidance" },
          { id: "fiu_txnmon_3", text: "Has the AI's false negative rate been assessed?", citation: "SR 11-7; FinCEN guidance" },
          { id: "fiu_txnmon_4", text: "Is tuning documented with rationale linked to risk assessments?", citation: "SR 21-8" },
          { id: "fiu_txnmon_5", text: "Does the AI appropriately escalate activity it cannot confidently classify?", citation: "BSA" },
          { id: "fiu_txnmon_6", text: "Is there human review of AI-generated alerts before final disposition?", citation: "BSA; FinCEN expectations" },
          { id: "fiu_txnmon_7", text: "Are monitoring scenarios updated to reflect current threats?", citation: "FinCEN advisories" },
          { id: "fiu_txnmon_8", text: "Is coverage tested against known typologies?", citation: "SR 11-7; FinCEN guidance" },
          { id: "fiu_txnmon_9", text: "Are audit trails complete for alert generation, investigation, and disposition?", citation: "BSA recordkeeping" },
        ],
      },
      {
        id: "fiu_cddedd",
        title: "BSA/AML: Customer Due Diligence (CDD/EDD)",
        triggerLabel: "RF10. AI used in KYC or risk rating.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [10] },
        questions: [
          { id: "fiu_cddedd_0", text: "Does the AI perform or assist with customer risk rating, KYC, or beneficial ownership analysis?", citation: "CDD Rule; 31 CFR §1010.230" },
          { id: "fiu_cddedd_1", text: "Are customer risk rating criteria documented?", citation: "CDD Rule" },
          { id: "fiu_cddedd_2", text: "Is the AI's identity verification accuracy validated?", citation: "CDD Rule" },
          { id: "fiu_cddedd_3", text: "Are EDD triggers properly calibrated?", citation: "CDD Rule" },
          { id: "fiu_cddedd_4", text: "Is there appropriate human oversight of AI-assisted CDD/EDD decisions?", citation: "CDD Rule" },
          { id: "fiu_cddedd_5", text: "Are CDD/EDD records maintained per BSA recordkeeping requirements?", citation: "BSA; 31 CFR §1010.430" },
        ],
      },
      {
        id: "fiu_sar",
        title: "BSA/AML: SAR Narrative and Case Management",
        triggerLabel: "RF10. AI used in SAR filing.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [2,3,4], riskFactors: [10] },
        questions: [
          { id: "fiu_sar_0", text: "Does the AI generate draft SAR narratives or assist in SAR filing?", citation: "BSA; 31 CFR §1020.320" },
          { id: "fiu_sar_1", text: "Is there mandatory human review and approval of all AI-generated SAR content before filing?", citation: "BSA; FinCEN expectations" },
          { id: "fiu_sar_2", text: "Are AI-generated narratives assessed for accuracy and FinCEN compliance?", citation: "BSA; FinCEN SAR Activity Review" },
          { id: "fiu_sar_3", text: "Does the AI have access to sensitive investigation data? Are access controls appropriate?", citation: "BSA tipping-off prohibitions" },
          { id: "fiu_sar_4", text: "Is investigation information protected from unauthorized disclosure?", citation: "18 U.S.C. §5318(g)(2)" },
          { id: "fiu_sar_5", text: "Are AI-assisted case management decisions auditable?", citation: "BSA recordkeeping" },
        ],
      },
      {
        id: "fiu_fraud",
        title: "Fraud Detection and Prevention",
        triggerLabel: "RF10. AI used in fraud detection.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [10] },
        questions: [
          { id: "fiu_fraud_0", text: "Does the AI score, alert, or block transactions for suspected fraud?", citation: "organization fraud program; Reg E" },
          { id: "fiu_fraud_1", text: "Are fraud scoring thresholds calibrated?", citation: "organization fraud risk appetite" },
          { id: "fiu_fraud_2", text: "Is the false positive rate monitored?", citation: "organization fraud program; MRM coordination" },
          { id: "fiu_fraud_3", text: "Is the false negative rate monitored against actual fraud losses?", citation: "organization fraud program; MRM coordination" },
          { id: "fiu_fraud_4", text: "Are fraud typologies updated to reflect AI-enabled fraud?", citation: "FinCEN advisories" },
          { id: "fiu_fraud_5", text: "Is there a customer notification process for AI-driven fraud blocks?", citation: "Reg E" },
        ],
      },
      {
        id: "fiu_ofac",
        title: "Sanctions / OFAC Screening",
        triggerLabel: "RF10. AI used in sanctions screening.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [10] },
        questions: [
          { id: "fiu_ofac_0", text: "Does the AI perform or assist with sanctions list screening or name matching?", citation: "OFAC regulations; 31 CFR Part 501" },
          { id: "fiu_ofac_1", text: "Is the name matching algorithm validated for accuracy?", citation: "OFAC guidance" },
          { id: "fiu_ofac_2", text: "Are fuzzy matching thresholds calibrated?", citation: "OFAC guidance" },
          { id: "fiu_ofac_3", text: "Are potential matches subject to mandatory human review before disposition?", citation: "OFAC expectations" },
          { id: "fiu_ofac_4", text: "Is screening coverage complete across all required transaction types?", citation: "OFAC regulations" },
          { id: "fiu_ofac_5", text: "Are screening lists updated at the required frequency?", citation: "OFAC regulations" },
          { id: "fiu_ofac_6", text: "Are blocked/rejected transactions reported to OFAC within required timeframes?", citation: "OFAC reporting; 31 CFR §501.603" },
          { id: "fiu_ofac_7", text: "Are audit trails maintained for all screening decisions?", citation: "OFAC recordkeeping" },
        ],
      },
    ],
  },
  PRIVACY: {
    key: "PRIVACY",
    label: "Privacy",
    sections: [
      {
        id: "privacy_pdi",
        title: "Personal Data Inventory",
        triggerLabel: "In scope when RF1 (PII/NPI/PCI) is set.",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [1] },
        questions: [
          { id: "privacy_pdi_0", text: "Has a complete inventory of personal data elements processed by the AI been documented (categories, sources, sensitivity)?", citation: "GLBA §501; Reg P; CCPA §1798.130" },
          { id: "privacy_pdi_1", text: "Are NPI elements specifically identified and tagged per GLBA definitions?", citation: "GLBA §501(b); Reg P §1016.3" },
          { id: "privacy_pdi_2", text: "Has the lawful basis or business purpose for each data category been documented?", citation: "CCPA §1798.100; CPRA; GDPR Art. 6" },
          { id: "privacy_pdi_3", text: "Are sensitive personal information categories (SPI under CPRA) identified separately?", citation: "CPRA §1798.140(ae); VCDPA §59.1-575" },
          { id: "privacy_pdi_4", text: "Is the data inventory reviewed and updated when AI capabilities or data flows change?", citation: "AI RMF Govern 1.4; CCPA §1798.130" },
        ],
      },
      {
        id: "privacy_ncf",
        title: "Notice, Consent, and Transparency",
        triggerLabel: "In scope when RF1 is set; depth added for RF2 (customer-facing).",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [1] },
        questions: [
          { id: "privacy_ncf_0", text: "Does the organization's privacy notice disclose AI/automated processing of personal information?", citation: "Reg P §1016.6; CCPA §1798.100; CPRA" },
          { id: "privacy_ncf_1", text: "For customer-facing AI, is the customer informed they are interacting with AI rather than a human?", citation: "State AI disclosure laws; UDAAP; CTDPA §6" },
          { id: "privacy_ncf_2", text: "Are opt-out mechanisms provided for automated decision-making or profiling where required?", citation: "CPRA §1798.185(a)(16); VCDPA §59.1-577; GDPR Art. 22" },
          { id: "privacy_ncf_3", text: "Is consent obtained where required prior to processing sensitive personal information by the AI?", citation: "CPRA §1798.121; GDPR Art. 9" },
          { id: "privacy_ncf_4", text: "Are notice and consent records retained in an auditable form?", citation: "CCPA §1798.130; GDPR Art. 7(1)" },
        ],
      },
      {
        id: "privacy_vdh",
        title: "Vendor Data Handling",
        triggerLabel: "In scope when RF1 is set; depth added for RF4 (vendor training) or RF6 (vendor processing).",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [1] },
        questions: [
          { id: "privacy_vdh_0", text: "Has a Data Processing Agreement (DPA) or equivalent contract clause been executed with the vendor?", citation: "GLBA §501(b); CCPA §1798.140(ag); GDPR Art. 28" },
          { id: "privacy_vdh_1", text: "Does the contract prohibit vendor use of organization data for model training or fine-tuning (RF4)?", citation: "the organization's standard AI contract terms; CCPA §1798.140(ag)(1)" },
          { id: "privacy_vdh_2", text: "Are sub-processors disclosed and approved, with flow-down privacy obligations?", citation: "GDPR Art. 28(2); CCPA §1798.140(ag)" },
          { id: "privacy_vdh_3", text: "Has the vendor's data residency, retention, and deletion practices been documented?", citation: "GDPR Art. 5(1)(e); CPRA §1798.100(a)(3)" },
          { id: "privacy_vdh_4", text: "Has a Privacy Impact Assessment (PIA) or DPIA been completed for vendor processing?", citation: "AI RMF Govern 1.5; GDPR Art. 35; CPRA §1798.185(a)(15)" },
        ],
      },
      {
        id: "privacy_dsr",
        title: "Data Subject Rights and Retention",
        triggerLabel: "In scope when RF1 is set; depth added for RF9 (persistent memory).",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [1] },
        questions: [
          { id: "privacy_dsr_0", text: "Can the AI system support consumer rights requests (access, deletion, correction, portability)?", citation: "CCPA §1798.105/.110/.115; CPRA; VCDPA §59.1-577" },
          { id: "privacy_dsr_1", text: "For systems with persistent memory (RF9), can stored context tied to a specific data subject be located and deleted on request?", citation: "GDPR Art. 17; CCPA §1798.105" },
          { id: "privacy_dsr_2", text: "Are retention periods defined for prompts, outputs, embeddings, and any cached personal data?", citation: "GLBA §501; GDPR Art. 5(1)(e); CPRA §1798.100(a)(3)" },
          { id: "privacy_dsr_3", text: "Are deletion procedures verified end-to-end including vendor-side stores and backups?", citation: "CCPA §1798.105(c); GDPR Art. 17(1)" },
          { id: "privacy_dsr_4", text: "Is there a documented process to honor opt-out of sale/sharing and limit use of SPI?", citation: "CCPA §1798.120; CPRA §1798.121" },
        ],
      },
      {
        id: "privacy_jur",
        title: "Jurisdictional Analysis",
        triggerLabel: "In scope when RF1 is set; depth added for RF2 (customer-facing across states).",
        triggers: { deliveryModels: [1,2,3,4], capabilityTiers: [1,2,3,4], riskFactors: [1] },
        questions: [
          { id: "privacy_jur_0", text: "Have all U.S. state privacy laws applicable to the organization's customer footprint been identified (CA, VA, CO, CT, UT, TX, etc.)?", citation: "CCPA/CPRA; VCDPA; CPA; CTDPA; UCPA; TDPSA" },
          { id: "privacy_jur_1", text: "Does processing trigger thresholds under any state comprehensive privacy law?", citation: "VCDPA §59.1-576; CTDPA §3; CPA §6-1-1304" },
          { id: "privacy_jur_2", text: "If EU/UK data subjects are in scope, has GDPR/UK GDPR applicability been assessed?", citation: "GDPR Art. 3; UK GDPR" },
          { id: "privacy_jur_3", text: "Are cross-border data transfer mechanisms in place where vendor processing occurs outside the U.S.?", citation: "GDPR Ch. V; SCCs; DPF" },
          { id: "privacy_jur_4", text: "Has counsel confirmed compliance with state AI-specific statutes (e.g., Colorado AI Act, NYC AEDT, IL BIPA where applicable)?", citation: "CO SB 24-205; NYC LL 144; IL BIPA" },
        ],
      },
    ],
  },
};
